---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
  namespace: monitoring
  labels:
    environment: prod
    monitoring: "true"
spec:
  type: LoadBalancer
  ports:
  - name: apps
    port: 80
    targetPort: 2112
  selector:
    name: go-prom